model:
  target: models.fusion.LightningFusion
  
  params:
    vision_input_dim: 2048
    motion_input_dim: 1024
    hidden_dim: 768 
    target_size: 2048
    device: cuda     
    lr: 6.0e-4
    scheduler_config:
      target: spamo.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        warm_up_steps: 1000
        lr_min: 0.01
        lr_max: 1.0
        lr_start: 0.01
        max_decay_steps: 125000
    t5_checkpoint: google/flan-t5-xl
    max_txt_len: 64
    # monitor: val/loss
    # beam_size: 5

lightning:
  callback:
    learning_rate_logger:
      target: pytorch_lightning.callbacks.LearningRateMonitor
      params:
        logging_interval: step
  trainer:
    accumulate_grad_batches: 2
    accelerator: gpu
    devices: 1
    max_epochs: 50
    gradient_clip_val: 1.0
    check_val_every_n_epoch: 2

data:
  target: dataset.fusion.FusionDataModule
  
  params:
    batch_size: 8
    num_workers: 4
    visual_features_path: features/vit_feat_pjm.h5
    motion_features_path: features/mae_feat_pjm.h5
    texts_path: features/texts.h5
    device: cuda
    max_frame_length: 512
    validation_proportion: 0.1
